---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: httpd-ds
  labels:
    app: webserver
    author: intelliqit
spec:
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      name: httpd-pod
      labels:
        app: webserver
    spec:
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 8080
...
