---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      name: mynginx
      labels:
        app: proxy
    spec:
      containers:
        - name: mynginx
          image: nginx
          ports:
            - containerPort: 80
              hostPort: 8080
          resources:
            requests:
              cpu: 200m
              memory: 64M
            limits:
              cpu: 500m
              memory: 128M
...

