---
apiVersion: v1
kind: Service
metadata:
  name: headless-service
  labels:
    app: db
spec:
  clusterIP: None
  ports:
    - targetPort: 3306
      port: 3306
  selector:
    app: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: db
spec:
  replicas: 2
  serviceName: headless-service
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      name: mysql-pod
      labels:
        app: db
    spec:
      containers:
        - name: mydb
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: intelliqit
          volumeMounts:
            - name: new-volume
              mountPath: /var/lib/mysql
      volumes: 
        - name: new-volume
          persistentVolumeClaim:
            claimName: my-pvc
... 




