---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  clusterIP: None
  ports:
    - targetPort: 80
      port: 80
  selector:
    app: proxy
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
  labels:
    app: proxy
spec:
  replicas: 2
  serviceName: nginx
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      name: nginx-pod
      labels:
        app: proxy
    spec:
      containers:
        - name: myngin
          image: nginx
          volumeMounts:
            - name: nginx-volume
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
       name: nginx-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1G
...

