---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    app: webserver
spec:
  containers:
    - name: myhttpd
      image: httpd
  tolerations:
    - key: node2
      value: intelliqit2
      effect: NoSchedule
      operator: Equal
...
